<?php

// comment out the following two lines when deployed to production
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';

//$config = require __DIR__ . '/../config/web.php';
//
//(new yii\web\Application($config))->run();

////////////////

$dbconn = pg_connect("host=localhost port=5432 dbname=carsdb user=admin password=12345")
or die('Не удалось соединиться c субд: ' . pg_last_error());

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
echo "    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\n";
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n";
echo "    <title>lab</title>\n";
echo "</head>\n";
echo "<body>\n";
echo "<div class=\"pos-f-t shadow\">\n";
echo "    <div class=\"collapse\" id=\"navbarToggleExternalContent\">\n";
echo "        <div class=\"bg-info\">\n";
echo "            <div class=\"container-fluid\">\n";
echo "\n";
echo "                <nav class=\"navbar navbar-expand-lg navbar-light bg-info\">\n";
echo "                    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n";
echo "                        <ul class=\"navbar-nav\">\n";
echo "                            <li class=\"nav-item active\">\n";
echo "                                <a class=\"nav-link\" href=\"#\"><div class=\"text-light\">Текущие турниры</div></a>\n";
echo "                            </li>\n";
echo "                            <li class=\"nav-item\">\n";
echo "                                <a class=\"nav-link\" href=\"#\"><div class=\"text-light\">Мои турниры</div></a>\n";
echo "                            </li>\n";
echo "                            <li class=\"nav-item\">\n";
echo "                                <a class=\"nav-link\" href=\"#\"><div class=\"text-light\">Прогнозы</div></a>\n";
echo "                            </li>\n";
echo "                            <li class=\"nav-item\">\n";
echo "                                <a class=\"nav-link\" href=\"#\"><div class=\"text-light\">О нас</div></a>\n";
echo "                            </li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "                    <div class=\"float-right text-light\">\n";
echo "                        <div class=\"links\">\n";
echo "                            <a class=\"navbar-brand\" href=\"#\" data-toggle=\"modal\" data-target=\"#exampleModal\">Вход</a>\n";
echo "                            <a class=\"navbar-brand\" href=\"#\" data-toggle=\"modal\" data-target=\"#exampleModal1\">Регистрация</a>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </nav>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"shadow-lg mb-5 bg-white rounded\">\n";
echo "        <nav class=\"navbar navbar-dark bg-info\">\n";
echo "            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarToggleExternalContent\" aria-controls=\"navbarToggleExternalContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
echo "                <span class=\"navbar-toggler-icon\"></span>\n";
echo "            </button>\n";
echo "            <div class=\"float-right text-light\">\n";
echo "                <h3><strong>BSTU </strong>Tournament Statistics</h3>\n";
echo "            </div>\n";
echo "        </nav>\n";
echo "\n";
echo "    </div>\n";
echo "</div>\n";
echo "\n";
echo "<div class=\"container-fluid\">\n";
echo "    <div class=\"row background\">\n";
echo "        <div class=\"col-2\">\n";
echo "            <div class=\"list-group\">\n";
echo "                <a href=\"#\" class=\"list-group-item list-group-item-action active bg-info\">\n";
echo "                    <strong>Список турниров</strong>\n";
echo "                </a>\n";
echo "                <a href=\"#\" class=\"list-group-item list-group-item-action\">Турнир памяти героя социалистического труда И.И.Пенкова</a>\n";
echo "                <a href=\"#\" class=\"list-group-item list-group-item-action\">Белгородский областной чемпионат по футболу</a>\n";
echo "                <a href=\"#\" class=\"list-group-item list-group-item-action\">Всеросийский чемпионат по волейболу среди ветеранов</a>\n";
echo "                <a href=\"#\" class=\"list-group-item list-group-item-action\">Первенство России среди команд молодежного состава</a>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <div class=\"col-10\">\n";
echo "            <div class=\"mx-auto\" style=\"width: 800px;\">\n";
echo "                <h2>Турнирная таблица</h2>\n";
echo "            </div>\n";
echo "            <div class=\"mx-auto\" style=\"width: 800px;\">\n";
echo "                <table class=\"table table-bordered\">\n";
echo "                    <thead>\n";
echo "                    <tr>\n";
echo "                        <th>Команда</th>\n";
echo "                        <th>Всего игр</th>\n";
echo "                        <th>Побед</th>\n";
echo "                        <th>Поражений</th>\n";
echo "                        <th>Ничьих</th>\n";
echo "                        <th>Очков</th>\n";
echo "                    </tr>\n";
echo "                    </thead>\n";
echo "                    <tbody>\n";
echo "                    <tr>\n";
echo "                        <td>Альфа</td>\n";
echo "                        <td>9</td>\n";
echo "                        <td>8</td>\n";
echo "                        <td>0</td>\n";
echo "                        <td>1</td>\n";
echo "                        <td>16</td>\n";
echo "                    </tr>\n";
echo "                    <tr>\n";
echo "                        <td>Крета</td>\n";
echo "                        <td>8</td>\n";
echo "                        <td>6</td>\n";
echo "                        <td>0</td>\n";
echo "                        <td>2</td>\n";
echo "                        <td>12</td>\n";
echo "                    </tr>\n";
echo "                    <tr>\n";
echo "                        <td>Сибериус</td>\n";
echo "                        <td>9</td>\n";
echo "                        <td>6</td>\n";
echo "                        <td>0</td>\n";
echo "                        <td>3</td>\n";
echo "                        <td>12</td>\n";
echo "                    </tr>\n";
echo "                    </tbody>\n";
echo "                </table>\n";
echo "            </div>\n";
echo "            <div class=\"mx-auto\" style=\"width: 100px;\">\n";
echo "                <h2>Итоги</h2>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class=\"mx-auto\" style=\"width: 300px;\">\n";
echo "                <table class=\"table table-bordered\">\n";
echo "                    <thead>\n";
echo "                    <tr>\n";
echo "                        <th>1 место</th>\n";
echo "                        <th>2 место</th>\n";
echo "                        <th>3 место</th>\n";
echo "                    </tr>\n";
echo "                    </thead>\n";
echo "                </table>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</div>\n";
echo "\n";
echo "<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n";
echo "    <div class=\"modal-dialog\" role=\"document\">\n";
echo "        <div class=\"modal-content\">\n";
echo "            <div class=\"modal-header\">\n";
echo "                <h5 class=\"modal-title\" id=\"exampleModalLabel\">Вход</h5>\n";
echo "                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n";
echo "                    <span aria-hidden=\"true\">&times;</span>\n";
echo "                </button>\n";
echo "            </div>\n";
echo "            <div class=\"modal-body\">\n";
echo "                <form>\n";
echo "                    <div class=\"form-group\">\n";
echo "                        <label for=\"exampleInputEmail1\">Адрес эл.почты</label>\n";
echo "                        <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter email\">\n";
echo "                    </div>\n";
echo "                    <div class=\"form-group\">\n";
echo "                        <label for=\"exampleInputPassword1\">Пароль</label>\n";
echo "                        <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"Password\">\n";
echo "                    </div>\n";
echo "                    <div class=\"form-group form-check\">\n";
echo "                        <input type=\"checkbox\" class=\"form-check-input\" id=\"exampleCheck1\">\n";
echo "                        <label class=\"form-check-label\" for=\"exampleCheck1\">Запомнить меня</label>\n";
echo "                    </div>\n";
echo "                    <button type=\"submit\" class=\"btn btn-info\">Войти</button>\n";
echo "                </form>\n";
echo "            </div>\n";
echo "            <div class=\"modal-footer\">\n";
echo "                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Закрыть</button>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</div>\n";
echo "\n";
echo "<div class=\"modal fade\" id=\"exampleModal1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n";
echo "    <div class=\"modal-dialog\" role=\"document\">\n";
echo "        <div class=\"modal-content\">\n";
echo "            <div class=\"modal-header\">\n";
echo "                <h5 class=\"modal-title\" id=\"exampleModalLabel1\">Регистрация</h5>\n";
echo "                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n";
echo "                    <span aria-hidden=\"true\">&times;</span>\n";
echo "                </button>\n";
echo "            </div>\n";
echo "            <div class=\"modal-body\">\n";
echo "                <form>\n";
echo "                    <div class=\"form-group\">\n";
echo "                        <label for=\"exampleName\">Имя пользователя</label>\n";
echo "                        <input type=\"text\" class=\"form-control\" id=\"exampleName\" placeholder=\"Enter name\">\n";
echo "                    </div>\n";
echo "                    <div class=\"form-group\">\n";
echo "                        <label for=\"exampleInputEmail1\">Адрес эл.почты</label>\n";
echo "                        <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail2\" aria-describedby=\"emailHelp\" placeholder=\"Enter email\">\n";
echo "                    </div>\n";
echo "                    <div class=\"form-group\">\n";
echo "                        <label for=\"exampleInputPassword2\">Пароль</label>\n";
echo "                        <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword2\" placeholder=\"Password\">\n";
echo "                    </div>\n";
echo "                    <div class=\"form-group\">\n";
echo "                        <label for=\"exampleInputCity\">Город</label>\n";
echo "                        <input type=\"text\" class=\"form-control\" id=\"exampleInputCity\" placeholder=\"City\">\n";
echo "                    </div>\n";
echo "                    <button type=\"submit\" class=\"btn btn-info\">Зарегистрироваться</button>\n";
echo "                </form>\n";
echo "            </div>\n";
echo "            <div class=\"modal-footer\">\n";
echo "                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Закрыть</button>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</div>\n";
echo "\n";
echo "<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\n";
echo "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\n";
echo "<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\n";
echo "</body>\n";
echo "</html>\n";

pg_close($dbconn);

?>


